name: Destroy Recursos

on:
  workflow_dispatch:
    inputs:
      confirm_destroy:
        description: 'Confirme para destruir todos os recursos'
        required: true
        default: 'no'

env: 
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  destroy_infrastructure:
    name: Destroy Recursos
    runs-on: ubuntu-latest
    if: github.event.inputs.confirm_destroy == 'yes'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.7.3

      - name: Terraform Init
        working-directory: ./infra
        run: terraform init

      - name: Terraform Plan
        working-directory: ./infra
        run: terraform plan

      - name: Terraform Destroy
        working-directory: ./infra
        run: terraform destroy -auto-approve
